---
- name: Install Docker dependencies with apt
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Install Docker dependencies with yum
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    update_cache: true
  when: ansible_os_family == "RedHat"
  become: true

- name: Add Docker’s official GPG key to apt
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"
  become: true

# TODO use lsb_release instead of hardcoded xenial
- name: Add Docker repository to apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Install Docker CE with apt
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Add Docker repository to yum
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "RedHat"
  become: true

- name: Install Docker CE with yum
  yum:
    name: [docker-ce, docker-ce-cli, containerd.io]
    update_cache: true
  when: ansible_os_family == "RedHat"
  become: true

- name: Add current user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: ['docker']
    append: true
  become: true

# Makes docker listen on 0.0.0.0 for remote access.
# Won't run unless the 'insecure' tag is specified.
- name: Create directory for docker.service override
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
  become: true
  tags: [never, insecure]

- name: Copy docker.service override for remote listening
  copy:
    src: files/startup_options.conf
    dest: /etc/systemd/system/docker.service.d/startup_options.conf
  become: true
  tags: [never, insecure]
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true
  tags: [never, insecure]

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Download and install Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  args:  
    creates: /usr/local/bin/docker-compose
  become: true

- name: Give docker-compose execute permissions
  file:
    path: /usr/local/bin/docker-compose
    mode: u+rx,g+rx,o+rx
  become: true
