---
- name: Install Docker dependencies with apt
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Install Docker dependencies with yum
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    update_cache: true
  when: ansible_os_family == "RedHat"
  become: true

- name: Add Docker’s official GPG key to apt
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Add Docker repository to apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_os_family == "Debian"
  become: true

# - name: Add Docker repository to yum
#  yum_repository:
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Add current user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: ['docker']
    append: true
  become: true

- name: Create directory for docker.service override
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
  become: true

- name: Copy docker.service override for remote listening
  copy:
    src: files/startup_options.conf
    dest: /etc/systemd/system/docker.service.d/startup_options.conf
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: restarted
  become: true
