---
- name: Install redis
  get_url:
    url: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/redis-stable.tar.gz
  register: rddownload

- name: Untar redis tar.gz file
  unarchive:
    src: /tmp/redis-stable.tar.gz
    dest: /tmp/redis-stable
  when: not rddownload.failed

- name: Make redis
  make:
    chdir: /tmp/redis-stable
    target: install
  become: true

- name: Start redis-server
  command: redis-server
  register: rdstart

- name: Test redis status
  command: redis-cli ping
  register: rdping
  failed_when: rdping.stdout != "PONG"
  when: not rdstart.failed
