---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 21, host: 2121"
      - "vm.network 'forwarded_port', guest: 20, host: 2020"
    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
