---
- name: Install Apache PHP module
  apt:
    name: 'libapache2-mod-fastcgi'
    update_cache: true
  become: true

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
  become: true

- name: Install PHP
  apt:
    name: ['php7.2', 'php7.2-fpm']
    update_cache: true
  become: true

- name: a2enmod FastCGI
  apache2_module:
    name: '{{ item }}'
  become: true
  with_items:
    - 'actions'
    - 'fastcgi'
    - 'alias'
    - 'proxy_fcgi'

- name: Update dir.conf
  copy:
    src: files/apache/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
  become: true

- name: Copy phpinfo page
  copy:
    src: files/info.php
    dest: '{{ document_root }}/info.php'
  become: true

- name: Copy default sites-available page
  template:
    src: files/apache/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: true

- name: Restart apache2
  service:
    name: apache2
    state: restarted
  become: true
