---
- name: Download and unpack bash tar.gz
  unarchive:
    src: https://ftp.gnu.org/gnu/bash/bash-3.0.tar.gz
    dest: /tmp/
    remote_src: true

- name: Install dependencies for compiling
  package:
    name: ['gcc', 'make', 'byacc']
  become: true

- name: Test if bash has already been compiled
  stat:
    path: /tmp/bash-3.0/bash
  register: compilation

- name: Run ./configure
  command: ./configure
  args:
    chdir: /tmp/bash-3.0
  when: not compilation.stat.exists

- name: make bash
  make:
    chdir: /tmp/bash-3.0
  when: not compilation.stat.exists

- name: Copy compiled bash binary to /bin/bash
  command: cp /tmp/bash-3.0/bash /bin/bash
  become: true

- name: Enable cgi-bin module
  file:
    src: "/etc/apache2/mods-available/cgi.load"
    dest: "/etc/apache2/mods-enabled/cgi.load"
    state: link
  when: enable_cgi_bin
  become: true

- name: Reload apache2
  service:
    name: apache2
    state: reloaded
  become: true

- name: Copy CGI script to cgi-bin
  copy:
    src: 'files/{{ cgi_script }}'
    dest: '/usr/lib/cgi-bin/{{ cgi_script }}'
    mode: 0755
  when: enable_cgi_bin
  become: true

- name: Copy index page for uptime cgi-script
  copy:
    src: 'files/html/uptime.html'
    dest: '/var/www/html/index.html'
    mode: 0644
  when: enable_cgi_bin and cgi_script == 'uptime.sh'
  become: true
