---
- name: Update apt and install redis
  apt:
    name: redis-server
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Update yum and install epel-release
  yum:
    name: "epel-release"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Update yum and install redis
  yum:
    name: "redis"
    state: present
    update_cache: true
  register: redis_installed
  when: ansible_os_family == "RedHat"

- name: Check if redis.conf is copied
  stat:
    path: /etc/redis.conf
  register: conf_exist

- name: Copy redis configuration
  copy:
    src: files/redis.conf
    dest: /etc/redis.conf
    mode: 0664
  become: true
  when:
    - conf_exist.stat.checksum is not defined or conf_exist.stat.checksum != "af4c43f989f03a677c927214efb58fc5b801183f"

- name: Check if redis service exists
  stat:
    path: /etc/rc.d/init.d/redis
  register: init_exist
  ignore_errors: true

- name: Copy redis service
  copy:
    src: files/redis_init_script
    dest: /etc/rc.d/init.d/redis
    mode: 0555
  become: true
  when:
    - init_exist.stat.exists == false
    - ansible_os_family == "RedHat"

- name: Check if rc.local is moved
  stat:
    path: /etc/rc.local
  register: rc_changed

- name: Copy rc.local
  copy:
    src: files/rc.local
    dest: /etc/rc.local
    mode: 0555
  register: rc_copied
  when:
    - rc_changed.stat.exists == true

- name: Start redis-server
  shell: redis-server > /dev/null
  args:
    creates: "/var/run/redis_{{ redis_port }}.pid"
  async: 45
  poll: 0
