language: python

services:
  - docker

install:
  - pip install molecule docker

script:
  - for D in roles/misc/*; do (cd $D && molecule lint); done
  - for D in roles/service/*; do (cd $D && molecule lint); done
  - for D in roles/vuln/*; do (cd $D && molecule lint); done
