version: '0.0.{build}-{branch}'
image: Ubuntu1804
platform: x64

skip_commits:
  files:
    - '**/*.md'

cache:
- /home/appveyor/.vagrant.d/boxes

install:
- sudo pip install molecule[ec2]
- molecule --version
- ansible --version

build_script:
- .testing/test-roles.sh aws
