version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo pip install molecule
      - run: molecule --version
      - run: ansible --version
      - run: .testing/test-roles.sh aws
