version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo pip install molecule docker
      - run: for D in roles/misc/*; do (cd $D && molecule lint); done
      - run: for D in roles/service/*; do (cd $D && molecule lint); done
      - run: for D in roles/vuln/*; do (cd $D && molecule lint); done