---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu1604
    box: ubuntu/xenial64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 5001"
  - name: centos7
    box: centos/7
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 5002"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ['701', '703']
verifier:
  name: goss
  lint:
    name: yamllint
