---
# tasks file for ftp
- name: Install the service
  include_tasks: install.yml

- name: Enable anonymous login
  include_tasks: anonymous_login.yml

- name: Enable user upload
  include_tasks: write_enable.yml
