---
# tasks file for ssh
- name: "Install {{ server_type }}"
  package:
    name: openssh-server
  become: true

- name: Start SSH server
  service:
    name: sshd
    enabled: true
    state: started
  become: true
