---
- name: Download and unpack bash tar.gz
  unarchive:
    src: https://ftp.gnu.org/gnu/bash/bash-3.0.tar.gz
    dest: /tmp/
    remote_src: true

- name: Install dependencies for compiling
  package:
    name: ['gcc', 'make', 'byacc']
  become: true

- name: Test if bash has already been compiled
  stat:
    path: /tmp/bash-3.0/bash
  register: compilation

- name: Run ./configure
  command: ./configure
  args:
    chdir: /tmp/bash-3.0
  when: not compilation.stat.exists

- name: make bash
  make:
    chdir: /tmp/bash-3.0
  when: not compilation.stat.exists

# TODO: Make idempotent
- name: Copy compiled bash binary to /bin/bash
  command: cp /tmp/bash-3.0/bash /bin/bash
  become: true
