---
- name: "Install {{ server_type }}"
  package:
    name: "{{ server_type }}"
    state: present
  become: true

# TODO: Change RedHat config to allow traffic from all interfaces.

- name: "Start {{ server_type }}"
  service:
    name: "{{ server_type }}"
    enabled: true
    state: started
  become: true
