---
- name: Test if redis command works
  command: redis-cli ping
  register: rdtestping
  ignore_errors: true

- fail:
    msg: "Redis is already up and running"
  when: not rdtestping.failed

- name: Make sure 'make' is installed on Debian
  package:
    name: build-essential
    state: present
  when: ansible_os_family == "Debian"

- name: Make sure 'make is installed' on RedHat
  yum:
    name: "@Development tools"
    state: present
  when: ansible_os_family == "RedHat"

- name: Download and untar redis tar.gz file
  unarchive:
    src: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp
    remote_src: true

- name: Make redis
  make:
    chdir: /tmp/redis-stable
    target: install
  become: true

- name: Start redis-server
  shell: redis-server
  async: 10
  poll: 0
  register: rdstart

- name: Test redis status
  command: redis-cli ping
  register: rdping
  failed_when: rdping.stdout != "PONG"
  when: not rdstart.failed
