---
- name: Update apt and install redis
  apt:
    name: redis-server
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Update yum and install epel-release
  yum:
    name: "epel-release"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Update yum and install redis
  yum:
    name: "redis"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Start redis-server
  command: redis-server
  register: redis_started
  async: 2592000
  poll: 0

- name: Test redis status
  command: redis-cli ping
  register: rdping
  failed_when: rdping.stdout != "PONG"
  when: redis_started.failed == false