---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      c: ~/.config/ansible-lint/config.yml
    enabled: false
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
